// automatically generated by the FlatBuffers compiler, do not modify

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type GarageDoorTrigger struct {
	_tab flatbuffers.Table
}

func GetRootAsGarageDoorTrigger(buf []byte, offset flatbuffers.UOffsetT) *GarageDoorTrigger {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GarageDoorTrigger{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *GarageDoorTrigger) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GarageDoorTrigger) Door() int16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *GarageDoorTrigger) MutateDoor(n int16) bool {
	return rcv._tab.MutateInt16Slot(4, n)
}

func (rcv *GarageDoorTrigger) Force() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *GarageDoorTrigger) MutateForce(n byte) bool {
	return rcv._tab.MutateByteSlot(6, n)
}

func GarageDoorTriggerStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func GarageDoorTriggerAddDoor(builder *flatbuffers.Builder, door int16) {
	builder.PrependInt16Slot(0, door, 0)
}
func GarageDoorTriggerAddForce(builder *flatbuffers.Builder, force byte) {
	builder.PrependByteSlot(1, force, 0)
}
func GarageDoorTriggerEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
